{{- if .Values.euler_copilot.vectorize.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: vectorize-secret-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  .env: |
    UVICORN_IP=0.0.0.0
    UVICORN_PORT=8001

    LOG=stdout
    
    DEVICE=cpu
    EMBEDDING_MODEL={{ .Values.euler_copilot.vectorize.model.embedding }}
    RERANK_MODEL={{ .Values.euler_copilot.vectorize.model.rerank }}
    MODEL_BASE_DIR=/vectorize-agent/models/
{{- end }}