{{- if .Values.euler_copilot.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  mysql-root-password: {{ .Values.euler_copilot.mysql.passwords.rootPassword }}
  mysql-password: {{ .Values.euler_copilot.mysql.passwords.userPassword }}
{{- end }}