{{- if .Values.euler_copilot.rag.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: rag-secret-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  .env: |
    UVICORN_IP=0.0.0.0
    UVICORN_PORT=8005
    SSL_ENABLE=
    SSL_CERTFILE=
    SSL_KEYFILE=
    
    LOG=stdout
    PYTHONPATH=./
    OEPKG_ASSET_INDEX_NAME=["27eb749adf6d4b498f6673d9ef719ef0"]
    GRAPH_RAG_ENABLE=
    
    UPLOAD_DOCS_PATH=
    RAG_KBA_UPDATE_URL=
    
    REMOTE_RERANKING_ENDPOINT=http://vectorize-agent-service-{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:8001/reranking
    REMOTE_EMBEDDING_ENDPOINT=http://vectorize-agent-service-{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:8001/embedding
    
    POSTGRES_HOST=pgsql-db-{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:5432
    POSTGRES_DATABASE=postgres
    POSTGRES_USER=postgres
    POSTGRES_PWD={{ .Values.euler_copilot.pgsql.passwords.userPassword }}
    
    NEO4J_URL=
    NEO4J_USERNAME=
    NEO4J_PASSWORD=
    
    DEFAULT_LLM_MODEL=qwen
    QWEN_MAX_TOKENS={{ .Values.globals.llm.openai.max_tokens }}
    QWEN_MODEL={{ .Values.globals.llm.openai.model }}
    QWEN_URL={{ .Values.globals.llm.openai.url }}/v1
    QWEN_KEY={{ .Values.globals.llm.openai.key }}
    TIMEOUT=60
    
    SPARK_KEY=
    SPARK_URL=
    SPARK_MODEL=
    
    SPARK_APP_ID=
    SPARK_APP_KEY=
    SPARK_APP_SECRET=
    SPARK_GPT_URL=
    SPARK_APP_DOMAIN=
    
    EMBEDDING_METHOD=offline
    EMBEDDING_METHOD_ONLINE=
    
    SPARK_QUERY_EMDEDDING=query-embedding
    SPARK_DOCS_EMDEDDING=docs-embedding
    SPARK_ENBEDDING_MODEL_URL=
    SPARK_ENBEDDING_MODEL_TRACEID=
    
    VERSION_EXPERT_LLM_MODEL=qwen
{{- end }}