{{- if .Values.euler_copilot.framework.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: framework-secret-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  .env: |
    UVICORN_PORT=8002
    UVICORN_HOST=0.0.0.0
    
    MYSQL_HOST='mysql-db-{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local'
    MYSQL_PORT=3306
    MYSQL_USER='euler_copilot'
    MYSQL_DATABASE='euler_copilot'
    MYSQL_CHARSET='utf8'
    MYSQL_PWD={{ .Values.euler_copilot.mysql.passwords.userPassword }}
    
    REDIS_HOST='redis-db-{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local'
    REDIS_PORT=6379
    REDIS_PWD={{ .Values.euler_copilot.redis.redisPassword }}
    
    EULER_HOME="https://openeuler.org/zh"
    
    RAG_QUERY_STREAM_QUESTION="http://rag-service-{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:8005/kb/get_stream_answer"
    RAG_KB_SN={{ .Values.euler_copilot.rag.knowledgebaseID }}
    
    LOG="stdout"
    
    SHORT_EXPIRE_TIME=5
    LONG_EXPIRE_TIME=30
    JWT_KEY={{ .Values.euler_copilot.framework.jwtKey }}
    
    COOKIE_DOMAIN={{ .Values.globals.domain }}
    
    DEPLOY_MODE=local
    
    LLAMA_MODEL={{ .Values.globals.llm.llama.url }}
    LLAMA_API_KEY={{ .Values.globals.llm.llama.key }}
    EMBEDDING_FILE_DIR=/model
    
    LLM={{ .Values.globals.llm.openai.model }}
    LLM_URL={{ .Values.globals.llm.openai.url }}
    LLM_KEY={{ .Values.globals.llm.openai.key }}
{{- end }}