{{- if .Values.euler_copilot.framework.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: framework-secret-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  .env: |
    UVICORN_PORT=8002
    UVICORN_HOST=0.0.0.0
    
    MYSQL_HOST='mysql-db-{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local'
    MYSQL_PORT=3306
    MYSQL_USER='euler_copilot'
    MYSQL_DATABASE='euler_copilot'
    MYSQL_CHARSET='utf8'
    MYSQL_PWD={{ .Values.euler_copilot.mysql.passwords.userPassword }}
    
    REDIS_HOST='redis-db-{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local'
    REDIS_PORT=6379
    REDIS_PWD={{ .Values.euler_copilot.redis.redisPassword }}
    
    EULER_HOME="https://openeuler.org/zh"
    
    RAG_HOST="http://rag-service-{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:8005"
    RAG_KB_SN={{ .Values.euler_copilot.rag.knowledgebaseID }}
    VECTORIZE_HOST="http://vectorize-agent-service-{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:8001"
    
    LOG="stdout"
    
    SHORT_EXPIRE_TIME=60
    LONG_EXPIRE_TIME=300
    JWT_KEY={{ .Values.euler_copilot.framework.jwtKey }}
    
    DOMAIN={{ .Values.globals.domain }}
    
    DEPLOY_MODE=local
    
    SCHEDULE_URL={{ .Values.globals.llm.scheduler.url }}
    SCHEDULE_API_KEY={{ .Values.globals.llm.scheduler.key }}
    
    MODEL={{ .Values.globals.llm.choice }}
    LLM_MODEL_NAME={{ .Values.globals.llm.openai.model }}
    LLM_URL={{ .Values.globals.llm.openai.url }}/v1
    LLM_KEY={{ .Values.globals.llm.openai.key }}
    
    POSTGRES_HOST=pgsql-db-{{ .Release.Name }}.{{ .Release.Namespace }}.svc.cluster.local:5432
    POSTGRES_DATABASE=postgres
    POSTGRES_USER=postgres
    POSTGRES_PWD={{ .Values.euler_copilot.pgsql.passwords.userPassword }}
    
    HALF_KEY1={{ .Values.euler_copilot.framework.half_keys.key1 }}
    HALF_KEY2={{ .Values.euler_copilot.framework.half_keys.key2 }}
    HALF_KEY3={{ .Values.euler_copilot.framework.half_keys.key3 }}
    
    PLUGIN_DIR=/euler-copilot-frame/apps/plugin
    SHELL_HOST=/euler-copilot-frame/config/host.json
    
    VOICE_URL={{ .Values.euler_copilot.framework.voice }}
{{- end }}